### ISSUE TITLE
Won't work when I try to change the audio src.

### ISSUE THREAD

**Issue by pfncfen** [thangngoc89/react-howler#10]
I wrote code like below in my web app

`<ReactHowler
          src={media[this.state.page].bgmUrl}
        />`

when I change the state like this:
`this.setState(
      {
        page: 3,
      }
    );`

the component won't work, it start to request hundreds of source mp3 files like this
![image](https://cloud.githubusercontent.com/assets/3774176/14844515/753936b0-0c8a-11e6-81d7-884d12351271.png)

What can I do?

**Comment by thangngoc89** [comment]
This looks like `media[this.state.page].bgmUrl` doesn't change after state changed. So howler.js downloaded the same file. 

Could you add some log to make sure `media[this.state.page].bgmUrl` was changed ?

**Comment by pfncfen** [comment]
`XMLHttpRequest cannot load http://www.stephaniequinn.com/Music/Allegro%20from%20Duet%20in%20C%20Major.mp3. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8000' is therefore not allowed access.
DemoComponent.js?582c:49 Now the src url is http://www.stephaniequinn.com/Music/Allegro%20from%20Duet%20in%20C%20Major.mp3
localhost/:1 XMLHttpRequest cannot load http://www.stephaniequinn.com/Music/Canon.mp3. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8000' is therefore not allowed access.
DemoComponent.js?582c:49 Now the src url is http://www.stephaniequinn.com/Music/Canon.mp3
localhost/:1 XMLHttpRequest cannot load http://www.stephaniequinn.com/Music/Allegro%20from%20Duet%20in%20C%20Major.mp3. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8000' is therefore not allowed access.`

Here's the log. According to it, the src did change after state changed. 

I read your source code, and the function componentWillReceiveProps made sure that when the props src is changed, the old howler will be destroyed and the new one will be initailized. So now I'm so confused about this problem.

**Comment by pfncfen** [comment]
Btw, I can still hear the sound even if the log tell me that XMLHttpRequest cannot load http://www.stephaniequinn.com/Music/Allegro%20from%20Duet%20in%20C%20Major.mp3. So I ignored this problem.

**Comment by thangngoc89** [comment]
> 'Access-Control-Allow-Origin' 

This is a common problem with hot-linking resources from other websites. You should download these files to your server/ or have a proxy that download these files on the fly. 

As you pointed out, `componentWillReceiveProps` make sure this kind of situation won't happen so I have no idea what may caused this.

**Comment by pfncfen** [comment]
I've realized the requirement in another way
`this.state = {
      page: 0,
      playing: [true, false, false, false]
    }

<div className="audio-container">
          {media.map(function (item, i) {
            return (<ReactHowler key={"howler"+i}
                                 src={item.bgmUrl}
                                 playing={this.state.playing[i]}
            />)
          })}
        </div>
`
using the playing array in this.state to control the whole React-howler group.

But the problem still exists. I think maybe it can be related to some low-level implementation of React. Some just keep on studying!  hahahaha

**Comment by thangngoc89** [comment]
Thanks for investigating this. Please let me know if you find a solution for this

**Comment by jgillich** [comment]
I have the same issue, changing the audio src causes the component to create infinite Howler instances.

**Comment by jgillich** [comment]
[My simplified version](https://github.com/cloudfm/cloudfm/blob/f858014cce50da4992e55b904471f0403dd1bf01/app/src/components/Howler.tsx) of this component works as expected. I'm not sure why it doesn't here (maybe because I'm using the master version and not beta?), but I've noticed a few other things:

* `this.howler = null` will not null the instance, you check for truthiness of the passed value in the setter
* `runIfSet(props.mute, this.mute(props.mute))` doesn't do what you expect it to do. Instead if passing a function, you pass the result of the function call. Note that you also never call `callback` in `runIfSet`.

**Comment by jgillich** [comment]
`componentWillReceiveProps` triggers `howl.play()` twice, first via `autoplay` in `initHowler` and another time in `toggleHowler`, so you're getting two plays with a single src change.

**Comment by thangngoc89** [comment]
@jgillich I don't use this component anymore so I'm looking for maintainer. I'm happy to give you write access to this repo.
