### ISSUE TITLE
Cannot set volume on Safari, iPhone or iPad

### ISSUE THREAD

**Issue by laurpantelimon** [thangngoc89/react-howler#100]
I cannot set volume on Safari, on either iPhone or iPad. Any ideas?

**Comment by Stenerson** [comment]
Is the example page working for you? As silly as it may sound, there have been multiple issues in the past where the mute switch is flipped, causing issues - could that be the case?

I just tried the example page on both of my iOS devices (iPad & iPhone each running iOS14) without any issues.

**Comment by laurpantelimon** [comment]
Yes, the problem is that I cannot mute it, not that it doesn't play. Also, the volume change does nothing.

**Comment by Stenerson** [comment]
Do the music player and basic function demos on https://howlerjs.com/ work for you? There's a volume slider on the music demo and a mute & volume test on the basic functions / core tests.
