### ISSUE TITLE
Upgrade howler

### ISSUE THREAD

**Issue by trivedi** [thangngoc89/react-howler#104]
Howler 2.2.0 doesn't function properly on iOS 14 and MacOS. Context:

Reported in Issue [1407](https://github.com/goldfire/howler.js/issues/1407)
Fixed in PR [1415](https://github.com/goldfire/howler.js/pull/1415)

A fix has been added to Howler 2.2.1.

Please upgrade.

**Comment by Stenerson** [comment]
@trivedi we're [using a caret](https://github.com/thangngoc89/react-howler/blob/09e56d7f6ad48cb06e1bde6cf10311e4faf4996a/package-lock.json#L2648) (`^`)  so you should be free to include `2.2.1` in your application, no worries. 

You can update the dependency without having to explicitly requiring howler yourself by running 
`npm install react-howler@latest`
