### ISSUE TITLE
Autoplay causing auto-restart when `src` is changed and `playing=true`

### ISSUE THREAD

**Issue by karlfloersch** [thangngoc89/react-howler#13]
If you change the source while playing=true, and then you pause and play again, you will notice the song restarts every time that you pause and replay.

To fix this simply remove `autoplay` from `initHowler()`. It's not actually required because you call `toggleHowler()` right after which will handle "autoplaying" the track.

```
  initHowler (props = this.props) {
    this.destroyHowler()
    if (typeof Howl !== 'undefined') { // Check if window is available
      this.howler = new Howl({
        src: props.src,
/* -       autoplay: props.playing,    <-- Remove me!      */
        mute: props.mute,
        loop: props.loop,
        onend: props.onEnd,
        onplay: props.onPlay,
        onpause: props.onPause,
        onload: props.onLoad,
        onloaderror: props.onLoadError
      })
    }
  }
```

You can see a fork of the repo in which I made the change here: https://github.com/karlfloersch/react-howler -- I didn't submit a PR because I messed with the repo to get `npm i --save https://github.com/karlfloersch/react-howler.git` to work.

**Comment by thangngoc89** [comment]
Thanks for pointing this out. I'll make a fix asap as well as install from github so you won't need to mess around with the repo

**Comment by thangngoc89** [comment]
Is there any solution to keep autoplay?

**Comment by karlfloersch** [comment]
I think that autoplay actually still works in that if you set `playing=true` when the file is loading. It's just that it doesn't use the autoplay feature of Howler. Though I could be wrong about this, I'm not completely sure what Howler's autoplay does

**Comment by thangngoc89** [comment]
Do you think this is a Howler's bug? I dont understand howler codebase either

**Comment by karlfloersch** [comment]
Honestly not sure. It definitely could be though but would require further investigation.

**Comment by Stenerson** [comment]
@karlfloersch, @thangngoc89 
I've been playing around with this today and I can definitely reproduce what you're reporting. Through some console debugging, it seems that the seek position gets stuck on the first position that's paused no matter what you do.

Example:

1. Auto play first file
2. Switch src to a new file
3. Pause (`Pos === 1.5`)
4. Play (`Pos === 1.5` but audio actually restarts)
5. Pause again in a different position (still `Pos === 1.5`)

I also tried to reproduce this in Howler with a [JSBin](https://jsbin.com/hikuzibefo/1/edit?js,console,output) and it seems to work there.

I need to retire for the afternoon but wanted to put some findings and my bin on here in case anyone else has ideas what could be causing this.

**Comment by thangngoc89** [comment]
@Stenerson this looks like a howler bug than our wrapper. Could you file a issue in howler repository?

**Comment by Stenerson** [comment]
@thangngoc89 That's what I thought at first too but my JSBin above basically replays exactly what we're doing in pure Howler and it seems to work fine.

That being said, I think I fixed the bug by not setting autoplay and just starting the audio after loading it. This is basically how Howler itself does autoplay so I don't see an issue with it.

```javascript
  /**
   * Create howler object with given props
   */
  initHowler (props = this.props) {
    this.destroyHowler()
    if (typeof Howl !== 'undefined') { // Check if window is available
      this.howler = new Howl({
        src: props.src,
        mute: props.mute,
        loop: props.loop,
        onend: props.onEnd,
        onplay: props.onPlay,
        onpause: props.onPause,
        onload: props.onLoad,
        onloaderror: props.onLoadError
      })

      // Start playing if props.playing is true
      if (props.playing) {
        this.play()
      }
    }
  }
```

Before committing I'd like to figure out **why** this is happening though.

**Comment by thangngoc89** [comment]
Ah. Thanks for clarify that. I'm fine with the workaround. But if you can find out about the root of the problem that's awesome

**Comment by Stenerson** [comment]
I've isolated the issue to be that we're calling `play()` immediately after invoking `autoplay`. If I don't call `play()` right after initializing, everything works great. I was also able to reproduce this in my (JSBin) as well by calling `play()` after auto starting.

I'm going to open a Howler bug but we can also play a little more nicely with Howler by changing `componentWillReceiveProps()` to not `toggleHowler` when the src is changing.

```javascript
  componentWillReceiveProps (props) {
    if (props.src !== this.props.src) {
      this.initHowler(props)
    } else {
      this.toggleHowler(props) // Moved this into an else rather than always calling it
    }
  }
```

**Comment by thangngoc89** [comment]
Awesome !!

**Comment by Stenerson** [comment]
FYI - Opened goldfire/howler.js#107
