### ISSUE TITLE
How to display seek/progress bar?

### ISSUE THREAD

**Issue by wmonecke** [thangngoc89/react-howler#130]
I am having some issues trying to display a seek bar where the user can click or scroll to different parts of the audio.

I saw the example at `FullControl.js` but it is still not clear to me how you would update the value.
I am controlling the audio from my redux store so I am trying to achieve something like:

`````
<ReactHowler
  onUpdateCurrentTime={(time) => dispatch(updateAudio(time))
/>
`````

I would then use the `time` to update the UI. 

Could you help me understand how I should approach this problem?

Thank you very much!

**Comment by Stenerson** [comment]
The FullControl example is using a [requestAnimationFrame](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame) polyfill (https://www.npmjs.com/package/raf) that uses a `ref` to call the `seek()` method ​

I'd probably [use a hook](https://reactjs.org/docs/hooks-reference.html#useref) these days, but the example using a `ref` to set `this.player`, then uses `this.player.seek()` to get the current position for each animation frame. 

```javascript
  renderSeekPos () {
    if (!this.state.isSeeking) {
      this.setState({
        seek: this.player.seek()
      })
    }
    if (this.state.playing) {
      this._raf = raf(this.renderSeekPos)
    }
  }
```

**Comment by wmonecke** [comment]
@Stenerson  Oh ok I am just very unfamiliar into `raf`. Thank you!

**Comment by Stenerson** [comment]
Yeah, I'm actually not too familiar with it but the important thing to know is that there's not a "seek updated" callback. You need to bring your own method of asking the player what the current seek position is. `raf` seem to be a fine method. Not sure if you could get away with a simple recursive `setTimeout` or not. There's probably some stuff out there comparing the two. Good luck!
