### ISSUE TITLE
@types/react-howler missing 'rate' prop

### ISSUE THREAD

**Issue by Yanxiazhii** [thangngoc89/react-howler#131]
in react-howler ReactHowler.js
![image](https://user-images.githubusercontent.com/91260886/145163993-7dfd4d9e-4884-4730-a0c4-edbe181c068b.png)

'rate' prop miss in @types/react-howler indes.t.ts
![image](https://user-images.githubusercontent.com/91260886/145164159-bc9c121c-ac92-4b47-b0ce-4f97c8c9cf55.png)

@types/react-howler version:3.7.2
react-howler version: 5.2.0

**Comment by Stenerson** [comment]
Should this be submitted to `DefinitelyTyped/DefinitelyTyped` or something like that? I don't use typescript and we don't maintain the typescript definitions. Thanks!

**Comment by Yanxiazhii** [comment]
> Should this be submitted to `DefinitelyTyped/DefinitelyTyped` or something like that? I don't use typescript and we don't maintain the typescript definitions. Thanks!

Yes, It should be submitted to `DefinitelyTyped`.Thank you for your reply!
