### ISSUE TITLE
Looking for maintainer

### ISSUE THREAD

**Issue by thangngoc89** [thangngoc89/react-howler#14]
I'm not using this package right now and I don't have anytime to maintain it. If you'd to do it, reply below and I'll grant you access to Github and npm

**Comment by Stenerson** [comment]
@thangngoc89 I'd be interested in helping out/collaborating but I don't feel quite up to the task of taking over as the only maintainer. 

Anyone else with me?!? :sweat_smile:

**Comment by thangngoc89** [comment]
@Stenerson thank you very much. 

This package is in a very good shape right now, but there is bugs that need to be fixed. So the main task is fixing bugs and cut releases (follow semver). 

If you have addition time, you might wanna to 

- Update to latest howler
- Add all howler's methods

The rest is up to you. 

Sounds good?

And what is your npm account ?

**Comment by Stenerson** [comment]
@thangngoc89 Sounds mostly good... I'm excited to be able to help but it's all kinda new to me. I'll maybe still be needing your help for a while but I'm up to the task!

I'm `stenerson` on npm (just created an account 😂 )

**Comment by thangngoc89** [comment]
I'll add you to npm ASAP. You need that to cut a release, if you can automate the process (by using https://github.com/semantic-release/semantic-release) it would be super cool. 

If you need anything, just ping me.

**Comment by thangngoc89** [comment]
@Stenerson Added you as a Collaborator on Github and npm 

Check it with 

```
$ npm owner ls react-howler
stenerson <stenerson.matt@gmail.com>
thangngoc89 <hi@khoanguyen.me>
```

**Comment by Stenerson** [comment]
@thangngoc89, I sent an email to you at your npm email address about publishing updates. Can you take a look and get back to me when you have a chance?

Thanks!

**Comment by thangngoc89** [comment]
Ouch. Sorry. I just saw your email. I'm writing an answer atm.

**Comment by Stenerson** [comment]
No worries at all! I just don't want to break anything for y'all 😹

**Comment by thangngoc89** [comment]
Don't worry. If you broke the package on npm, you dist-tag latest to a previous version of it 

https://docs.npmjs.com/cli/dist-tag
