### ISSUE TITLE
update dependencies

### ISSUE THREAD

**Issue by ashwin31** [thangngoc89/react-howler#25]
Hi @thangngoc89 can you update dependencies as i see few are old https://www.versioneye.com/nodejs/react-howler/3.4.0

**Comment by thangngoc89** [comment]
@ashwin31 Thank you
@Stenerson do you have time to do the update? I suggest you use semantic versioning: `howler: "^2.0.0` this would prevent us from having this kind of issue

**Comment by Stenerson** [comment]
Yes, thanks @ashwin31 & @thangngoc89!
I must have accidentally removed the caret from howler when I updated it to 2.0 a while back and it's been a while since I've updated the dev dependencies.

I'll release an update soon. I assume this just calls for a patch release -`3.4.1`?

**Comment by thangngoc89** [comment]
@Stenerson yup. This is def a patch
