### ISSUE TITLE
Getting error on, after install, on "npm run start"

### ISSUE THREAD

**Issue by j-verre** [thangngoc89/react-howler#3]
I am currently getting unresolved modules errors when trying to 'npm run start' within my react-redux project:
'Module not found' for the following:
> babel-runtime/helpers/classCallCheck
> babel-runtime/core-js/object/get-prototype-of 
> babel-runtime/helpers/createClass
> babel-runtime/helpers/inherits
> in .../node_modules/react-howler/lib @ ./~/react-howler/lib/ReactHowler.js 7:22-78
My guess is that it's most likely a Babel runtime/version issue.

However, I'm getting an error trying to run your project by itself. After 'npm install' on the 'examples/react' directory, the 'npm run start' fails.
Trying to run the start script:
> "start": "webpack-dev-server --config webpack.config.js --watch --progress --color --hot --port 3000",

**Comment by thangngoc89** [comment]
Are you on npm@2 ?  I researched this error.  It looks like npm@3 is the only solution.

By the way,  `react-howler` is shipped with es5 code in npm.  The only dependency is howler.js.  I'll see what I can do with this

**Comment by j-verre** [comment]
Yes, npm 2.14.7
We have no plans upgrade during this phase of development. I'll look around if I get a chance.
Thanks.

**Comment by Stenerson** [comment]
I'm having the same issues I upgraded to the latest npm `3.5.3` with no luck.

**Comment by Stenerson** [comment]
I ran `npm update` and it's building now.

Not sure if that's an advisable solution but it seemed to get me past this.

**Comment by thangngoc89** [comment]
@Stenerson, @j-verre did you ran `npm install` inside `examples/react` folder ? 
The examples is a standalone project that comsumes `react-howler` it doesn't use dependencies from `react-howler`

**Comment by Stenerson** [comment]
@thangngoc89 I wasn't using the examples. 
I ran `npm -i react-howler --save` from my project root.

I'm using gulp and browserify/babelify to build. I was getting the same errors as @j-verre. I upgraded to npm@3 as you suggested and the issue was the same. Once I ran `npm update` it's building fine. I'm not sure if my babel version was out of date or what it might have been. I did try updating babel before upgrading to npm@3 and that didn't fix it.

**Comment by thangngoc89** [comment]
@Stenerson thank you for you information. Sadly, I'm don't use browserify. From the error @j-verre provided, all I can say is babel trying to babelify `react-howler` code, which is already in ES5. 

Is your project public ? Could you send me a link?

**Comment by Stenerson** [comment]
It's not public but like I said it's building now so I think I'm good, at least for the build.

**Comment by thangngoc89** [comment]
@Stenerson ok, I'm refactoring dependencies here https://github.com/thangngoc89/react-howler/pull/4.
Hope It'll work in npm@2 again

**Comment by thangngoc89** [comment]
@j-verre fixed in `react-howler@1.0.1`

Could you update and confirm ?

**Comment by thangngoc89** [comment]
ping @j-verre

**Comment by j-verre** [comment]
@thangngoc89 Noticed you were doing some work a few minutes ago. Do you want me to wait or retry? When ready I will grab a fresh copy of the project.

**Comment by thangngoc89** [comment]
@j-verre you can try with 1.0.2. I didn't release new version yet :)

**Comment by j-verre** [comment]
@thangngoc89 It seems to be better, the babel-runtime-errors are gone and it built but running the app gave me the error...
`Uncaught Error: Cannot find module "react-howler"`
for the `import Audio from 'react-howler'` statements in AutoPlay.js, OnlyPlayPauseButton.js, and FullControl.js

**Comment by thangngoc89** [comment]
@j-verre are you installing `react-howler` as dependencies in your project or cloning it from github ? 

For master branch on github, after cloning it, run these command inside `react-howler` folder:

```shell
npm install
cd examples/react 
npm install
npm start
```

open http://localhost:3000

I'll update README.md to be more specific about this :) 

I added automatic build in Travis for node 4 and npm@2 so I can make sure this will work

**Comment by j-verre** [comment]
@thangngoc89 My project is a dependency not cloning from github.
Following the above it fails at `npm start`
```
Failed at the react-howler-example@ start script 'webpack-dev-server --config webpack.config.js --watch --progress --color --hot --port 3000'.
 70% 1/1 build modulesevents.js:141
      throw er; // Unhandled 'error' event
      ^
```
Just wondering why you are using port 3000 when the 'webpack-dev-server' default is 8080?

**Comment by thangngoc89** [comment]
@j-verre you can't run example when install it via npm. (some minor conflict)

fyi, port 8080 was used by npm_lazy in my laptop

**Comment by j-verre** [comment]
@thangngoc89 `npm run example:react:start` is not available
trying npm run example:react:build now...

**Comment by thangngoc89** [comment]
How did you install `react-howler` ? To run example,  you had to clone the repo

**Comment by j-verre** [comment]
I did git clone the 2.0.0 repo to a directory on my desktop.

However, after it failed I went into the examples directory and changed the port to 8008 in webpack.config (entry) and package.json (start script) then it built and ran fine.
So that looks good.

**Comment by thangngoc89** [comment]
glad to hear it

**Comment by j-verre** [comment]
looks good, thanks for working on this issue

**Comment by thangngoc89** [comment]
Closed by now.  Feel free to reopen it
