### ISSUE TITLE
Does not player when props change

### ISSUE THREAD

**Issue by rockyasante** [thangngoc89/react-howler#30]
Ideally, ReactHowler should automatically stop and reset itself when  new props are passed and ComponentDidUpdate method is called.

I may be missing something, but its no stated in your docs on how to pass in new src for howler.

**Comment by Stenerson** [comment]
Hi @rockyasante, 
We do [actually](https://github.com/thangngoc89/react-howler/blob/master/src/ReactHowler.js#L15) destroy the Howler instance and re-initialize when the src prop changes.

```js
  componentWillReceiveProps (props) {
    if (props.src !== this.props.src) {
      this.initHowler(props)
    } else {
      this.toggleHowler(props)
    }
  }
```

You're 💯 correct that the docs should be more clear on this. I'll leave this open until I have a little time to update the docs (and maybe create an example with the source changing).

**Comment by rockyasante** [comment]
Thanks @Stenerson , I saw that bit of code after writing the this. However it does not actually work,  maybe it is done by design to allow us to do what we want with the player. Ideally, it should play automatically without us doing much to it. Considering that this will only be used as a "dummy" component that will only play a URL.  Also currently there is not an outstanding react music player and ReactHowler looks like is much higher that all the rest we looked at. Thanks for this

**Comment by Stenerson** [comment]
Hi @rockyasante, It should be working as I described - if it's not it may be a bug. I threw together a quick example component that uses react-howler to switch sources on the fly and it is working as expected for me. I'll add this as an example to the demo site once I can work through #29. For now, I'll include it below.

Keep in mind also that the file needs to load before it plays. Large files can have considerable lag to load before playing, especially if loading from a remote location.  I'm using pretty small files in the examples, specifically for this reason. 

If you're playing large files you may consider spinning up multiple ReactHowler components at the same time but only playing one of them. That way you can preload all of the sources and just switch which ReactHowler component is `playing`.

Hopefully this helps. If you have any more details that could help me track this down that'd be great! Here's the component that I used to test the source swap.

```js
import React from 'react'
import ReactHowler from 'ReactHowler'

class SwapSource extends React.Component {
  constructor (props) {
    super(props)

    // The two files that we'll switch between
    this.sources = ['sound.ogg', 'sound3.ogg']

    this.state = {
      currentSrcIndex: 0,
      playing: false
    }

    this.handleSwap = this.handleSwap.bind(this)
    this.handlePlay = this.handlePlay.bind(this)
    this.handlePause = this.handlePause.bind(this)
  }

  handleSwap () {
    // Just switch back and forth between 0 and 1
    let nextIndex = this.state.currentSrcIndex === 0 ? 1 : 0
    this.setState({currentSrcIndex: nextIndex})
  }

  handlePlay () {
    this.setState({
      playing: true
    })
  }

  handlePause () {
    this.setState({
      playing: false
    })
  }

  render () {
    return (
      <div>
        <ReactHowler
          playing={this.state.playing}
          // When the sources are swapped we'll pass a new
          // src prop into ReactHowler which will destroy our
          // currently playing Howler.js and initialize
          // a new Howler.js instance
          src={this.sources[this.state.currentSrcIndex]}
        />
        Currently playing {this.sources[this.state.currentSrcIndex]}
        <br />
        <button onClick={this.handlePlay}>Play</button>
        <button onClick={this.handlePause}>Pause</button>
        <button onClick={this.handleSwap}>Swap Source</button>
      </div>
    )
  }
}

export default SwapSource
```

**Comment by Stenerson** [comment]
@rockyasante Feel free to reopen this if you're still having issues or have suggestions to improve the doc. 

Happy howling! 🐵

**Comment by rockyasante** [comment]
Mate, the issue was html=true for streaming files. Is all in your docs, it works nicely. Great work!
