### ISSUE TITLE
Examples don't work in Safari or Safari Mobile

### ISSUE THREAD

**Issue by Stenerson** [thangngoc89/react-howler#32]
The example sounds are `ogg`s which are [apparently not supported by Safari or Mobile Safari](https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats) - somehow I never noticed this until now. We should choose some example audio clips that work across the three major browsers. Probably use Howler's example sounds if possible.

**Comment by Stenerson** [comment]
If it's not working for you, and you end up here. Make sure your phone isn't on silent! 😂

Safari not supporting `ogg` **was** the original issue but I was seeing some really odd behavior, even after adding the mp3s. It turned out that my phone was on silent. Need more ☕️ I guess!

**Comment by willowTank** [comment]
I met such problem So did you fix by using MP3

**Comment by Stenerson** [comment]
Yes, take a look at the example sources. I’m now using both MP3 (for most browsers) and (ogg) for Firefox.

**Comment by willowTank** [comment]
Thanks for your replay

**Comment by willowTank** [comment]
I want to play it on Android Browser but I cann't do it.

`<ReactHowler src= "/sounds/lost.ogg" playing={this.state.isPlay===3}  ref={(ref) => (this.lostPlayer = ref)}/>`

**Comment by Stenerson** [comment]
Do [the examples](https://khoanguyen.me/react-howler/) work on that browser? Are you getting any errors in the console?
