### ISSUE TITLE
React-native support?

### ISSUE THREAD

**Issue by ravigadila** [thangngoc89/react-howler#33]
Does this library support react-native in any way? Do you plan to support react-native in future?

**Comment by Stenerson** [comment]
That's a good question @ravigadila. Other than a few hello world apps I made out of curiosity, I haven't really used react-native. 

I looked around the web a bit to see if Howler.js was being used in other react-native libraries. I did find [this issue](https://github.com/jsierles/react-native-audio/issues/85) on another project where someone is using Howler.js (not related to said project) inside of a WebView to play sounds. Without knowing too much about react-native, that sounds like a promising (albeit slightly hacky) approach. I guess you'd just wrap `<ReactHowler>` with a `<WebView>`? 

The [Howler.js](https://github.com/goldfire/howler.js) library that we're wrapping is very specifically made to run in a browser. If this (or a similar approach) doesn't work, we're probably not the library for react-native.

What do you think?

**Comment by ravigadila** [comment]
Thanks for quick reply @Stenerson. We already using `react-howler` in our online streaming react based web app It works great.

We started mobile app in react-native for the same site. I don't want to use `<WebView>`. I expected Platform(Ios/android) specific implementation of howler.js.
