### ISSUE TITLE
Can't play sound before component unmounts

### ISSUE THREAD

**Issue by sAs59** [thangngoc89/react-howler#36]
`componentWillUnmount() {
    this.player.howler.play()
  }`

**Comment by Stenerson** [comment]
`play()` actually does get called but then the sound is immediately destroyed (and thus will not play) when the `ReactHowler` component is unmounted:

```js
  /* ReactHowler.js */
  componentWillUnmount () {
    this.destroyHowler()
  }

  // ...

  /**
   * Stop, unload and destroy howler object
   */
  destroyHowler () {
    if (this.howler) {
      this.howler.off() // Remove event listener
      this.howler.stop() // Stop playback
      this.howler.unload() // Remove sound from pool
      this.howler = null // Destroy it
    }
  }
```

I'm not sure if it's possible to change this behavior. Since ReactHowler itself is probably being unmounted in your example I think the sounds that it owns will be dereferenced and marked for garbage collected anyway.

Can you help me understand the use case to play on unmount?

**Comment by sAs59** [comment]
I wanted to make sound effect when moving from one component to another. Thought componentWillUnmount is the place where I should play sound. But, now I realized, it can be done in componentDidMount of another component.
Sorry...

**Comment by Stenerson** [comment]
No worries! `componentDidMount` would be a good place, as long as the sound file is preloaded or cached. If that's not the case you may want to place ReactHowler somewhere else in your component tree or just use Howler directly somewhere in your app to allow for better Howl lifecycle control.

Happy Howling! 😎

**Comment by sAs59** [comment]
@Stenerson  Could you, please, give a little help? I just want to use play method of howler.  So, how can I make reusable function for playing sound from any component?  Like:
```JavaScript 
import { play } from 'sounds'

onClick={ () => { play('click') }}
```
Instead of it, for playing sound, i have to: import 'react-howler', get reference of it and then call play.
```JavaScript 
import Howler from 'react-howler'

class MyComponent extends Component {
  playSound() {
    this.player.howler.play()
  } 

  render() {
     return (
       <Howler 
         src="click.mp3"
         playing={false}
         ref={(ref) => this.player = ref}
       />
       <div onClick={() => { this.playSound() }}
     )
  }
}
```
Thanks!

**Comment by thangngoc89** [comment]
@sAs59 Please refer to this sample example for more information https://github.com/thangngoc89/react-howler/blob/master/examples/react/src/players/AutoPlay.js

You need to change playing from `false` to `true` and Howler will play it for you. Only use ref if you need to access Howler instance.

**Comment by sAs59** [comment]
@thangngoc89 Saying sounds I mean 1-2 sec sfx sounds. I'd like to play sound on every mouse click.

**Comment by thangngoc89** [comment]
@sAs59 I think you should use howler.js directly, you'll have more control. https://github.com/goldfire/howler.js/ (look for audio sprites)

**Comment by sAs59** [comment]
@thangngoc89 ok, thanks.
