### ISSUE TITLE
Play/pause/seek actions are adding another sound to the Howl instance

### ISSUE THREAD

**Issue by TrevorHinesley** [thangngoc89/react-howler#37]
As the title suggests, if I change the `playing` prop, or call `this.reactHowlerRef.seek(position)`, etc., it's adding another sound to the Howl instance, which causes all sorts of audio madness.

**Comment by TrevorHinesley** [comment]
This works with howler 2.0.2, but the latest release breaks it.

**Comment by Stenerson** [comment]
Thanks for reporting @TrevorHinesley! Can you try with [`2.0.4`](https://github.com/goldfire/howler.js/releases/tag/v2.0.4)? It looks like a number of defects were addressed in this release.

**Comment by Stenerson** [comment]
@TrevorHinesley, are you still experiencing this?

**Comment by TrevorHinesley** [comment]
I haven't tried with the newest version, been slammed! Sorry :/

**Comment by Stenerson** [comment]
@TrevorHinesley, I'm going to close this for now. If you're still having issues after trying with another Howler version, please reopen.
