### ISSUE TITLE
Use fixed howler version

### ISSUE THREAD

**Issue by thangngoc89** [thangngoc89/react-howler#39]
After a quick look via commit history of howler.js. I can say that they don't follow semver. So I suggest we use a fixed version of howler to avoid weird bug like #37 .

What do you think @Stenerson ?

**Comment by Stenerson** [comment]
I think that probably makes sense. Do you have a version in mind? Should we lock on `2.0.2` for now and upgrade periodically with new react-howler changes (including testing the newly upgraded version of howler before updating)?

**Comment by thangngoc89** [comment]
@Stenerson I'm not sure which version we should use. How about fixing #38 and use the current version?

**Comment by Stenerson** [comment]
Sounds like as good a plan as any! 👍
