### ISSUE TITLE
React 16

### ISSUE THREAD

**Issue by Stenerson** [thangngoc89/react-howler#46]
Looking for feedback on the best way to support React 16. 

I've seen a few libraries use
```js
"peerDependencies": {
  "react": ">=0.14",
  "react-dom": ">=0.14"
},
```

We could also add more "ors"
```js
"peerDependencies": {
  "react": "^0.14.0 || ^15.0.0-0 || ^16.0.0-0",
  "react-dom": "^0.14.0 || ^15.0.0-0 || ^16.0.0-0"
},
```
Note: this doesn't cover the betas but we could add those as well.

Thoughts on the correct approach? Is support for React 0.14 still needed?

**Comment by Stenerson** [comment]
Thinking out loud: There's probably no reason to drop support for React 0.14 until we use features/apis that are not available in that version (probably never).

**Comment by thangngoc89** [comment]
@Stenerson actually, I see a few libraries just drop the peerDep requirements entirely. Since some people might want to use the component with something like preact-compat or inferno-compat. And we're using public API only so I think it's safe to drop the peerDep. Thoughts?

**Comment by Stenerson** [comment]
That's an interesting option @thangngoc89 - I hadn't even thought of that as a possibility. Would we keep React in devDependencies then or remove it entirely?

**Comment by thangngoc89** [comment]
@Stenerson we should keep the devDependencies. It won't be installed on user's end and we need it for development anyway
