### ISSUE TITLE
Get information about the error?

### ISSUE THREAD

**Issue by Skit** [thangngoc89/react-howler#48]
How do I get information about the error?
`  <ReactHowler`
                    `    src={this.state.stream.src}`
                       ` onLoadError={this.handleOnLoadError}`
                       ` onLoad={this.handleOnLoad}`
                       ` onPlay={this.handleOnPlay}`
                        `preload={false}`
                        `playing={this.state.isPlay}`
                        `html5={true}`
                        `format={[this.state.stream.type]}`
                        `ref={(ref) => (this.player = ref)}`
                    `/>`

`/* */`
`constructor(props) {
        super(props);`
`//.....`
`this.handleOnLoadError = this.handleOnLoadError.bind(this);`
`}`

`/* */`
`    handleOnLoadError(){`
  `console.log('handleOnLoadError');`
`    }`

[console.log screen](https://s.mail.ru/MkTx/xMy6dS4xt)
Thanks!

**Comment by Stenerson** [comment]
Howler will execute this callback with a string parameter explaining the error.

Try this in your code:
```javascript
handleOnLoadError(message){
  console.log(message);
}
```

You can see the possibilities in the Howler code itself if you search for `loaderror`.

Some examples:
[Line 587](https://github.com/goldfire/howler.js/blob/92dc9d6cdb3ab3d83c3a8f41c145d6751b01c13e/src/howler.core.js#L587)  `self._emit('loaderror', null, 'No codec support for selected audio sources.');`
[Line 2105](https://github.com/goldfire/howler.js/blob/92dc9d6cdb3ab3d83c3a8f41c145d6751b01c13e/src/howler.core.js#L2105) `self._emit('loaderror', null, 'Failed loading audio file with status: ' + xhr.status + '.');`
[Line 2150](https://github.com/goldfire/howler.js/blob/92dc9d6cdb3ab3d83c3a8f41c145d6751b01c13e/src/howler.core.js#L2150) `self._emit('loaderror', null, 'Decoding audio data failed.');`

**Comment by Skit** [comment]
Thanks!

    handleOnLoadError(message){

        if(message !== null){ /* */
}
I get the call twice (when have an error and not), probably that`s ok.
