### ISSUE TITLE
Does React Howler support howler spatial plugin?

### ISSUE THREAD

**Issue by tomohisaota** [thangngoc89/react-howler#49]
I am using React Howler, and trying to use stereo method of howler.
I save reference to _audioPlayer variable, and I can play audio by calling _audioPlayer.play() method.
But calling _audioPlayer.howler.stereo(1.0) does not seem to have any effect.
Audio source is in stereo MP3 format.

Stereo function is provided by spatial plugin.
Can I use spatial plugin with React Howler?

**Comment by Stenerson** [comment]
To be honest I've never used to the spatial plugin and don't know anything about it other than reading through its example code. 

We don't have any of the spatial methods or properties built in but you should be able to access them using the `howler` property as [shown in the readme](https://github.com/thangngoc89/react-howler#other-howlerjs-methods). I'm not sure if this will work well for your use-case but hopefully it helps.

**Comment by tomohisaota** [comment]
Thank you for the advice. I will give it a try.
