### ISSUE TITLE
Returning invalid element type?

### ISSUE THREAD

**Issue by Stenerson** [thangngoc89/react-howler#5]
Not sure if this a bug, a user error or something else entirely. I'm getting errors when trying to include the ReactHowler component in a simple container component that I created.

Here's the container component `HowlerButton`.

```
var React = require('react');
var ReactHowler = require('react-howler');
var classnames = require('classnames');

var HowlerButton = React.createClass({

  getInitialState() {
    return {
      isPlaying: false
    };
  },

  render() {
    return (
      <span>
        <ReactHowler src={this.props.src} playing={this.state.isPlaying} />
        <button className={this.props.className} onTouchTap={this._togglePlaying}>
          <i
            className={classnames("fa", {"fa-volume-up": !this.state.isPlaying, "fa-pause": this.state.isPlaying})}
            style={{marginRight: ".25em", marginLeft: ".25em"}}
          />
          {!this.state.isPlaying ? this.props.playText : this.props.pauseText}
        </button>
      </span>
    );
  },

  _togglePlaying() {
    this.setState({isPlaying: !this.state.isPlaying});
  }

});

module.exports = HowlerButton;
```

When this component is rendered by its parent I get the following errors in the console.

```
warning.js:45 Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `HowlerButton`.

invariant.js:39 Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `HowlerButton`.
```

If I remove the `ReactHowler` component the button renders fine.

Any ideas? Thanks in advance!!

**Comment by thangngoc89** [comment]
It looks like `ReactHowler` is `null, undefiend, boolean, or number`
Could you `console.log(ReactHowler)` inside render method ?

**Comment by thangngoc89** [comment]
FYI, I'm using babel 6 so you mind have to require `ReactHowler` at 

`var ReactHowler = require('react-howler').default` 

Ref: http://stackoverflow.com/questions/33505992/babel-6-changes-how-it-exports-default

I'm publish a new version to fix this asap

**Comment by Stenerson** [comment]
Thanks @thangngoc89 adding `.default` worked!

Before I added `.default`, `console.log(ReactHowler)` was only returning the `Howler` global object.

**Comment by thangngoc89** [comment]
@Stenerson published 1.0.0

You can use CommonJS require style normally:

`var ReactHowler = require('react-howler');`

Thanks for reporting this issue.
Feel free to reopen this.

**Comment by Stenerson** [comment]
@thangngoc89, I ran `npm uninstall react-howler` and `npm install react-howler --save`

My `package.json` was updated to `"react-howler": "^1.0.0"` but it's still requiring me to specify the default object. 

The component is working great and I don't necessarily mind the extra word in the require statement but I'm happy to help verify this if there's something else I could do.

Thanks for all the help today!

**Comment by thangngoc89** [comment]
@Stenerson thanks for debugging with me. I'll see what I can do to work around this babel issue. I the mean time, please require `react-howler` with `default`. 

Sorry for all the troubles, this is my first time publish a React component with ES6 code

**Comment by thangngoc89** [comment]
@Stenerson could you try `react-howler@1.0.2` ?

**Comment by Stenerson** [comment]
Confirmed *Fixed* in `1.0.2`! Nice work.

**Comment by thangngoc89** [comment]
Thanks.

**Comment by Stenerson** [comment]
For the record, here's my "completed" `HowlerButton` component in case it's any use to you or anyone else. It's pretty similar to your examples but I thought I'd include it just it case. Thanks again for all the help.

The icons are using font-awesome classes and the component uses the excellent classnames package.

```
var React = require('react');
var ReactHowler = require('react-howler');
var classnames = require('classnames');

var HowlerButton = React.createClass({

  getDefaultProps: function() {
    return {
      showText: true,
      showIcon: true,
      playIcon: "fa-volume-up",
      pauseIcon: "fa-pause",
      playText: "Play",
      pauseText: "Pause"
    };
  },

  getInitialState() {
    return {
      isPlaying: false
    };
  },

  render() {
    return (
      <span>
        <ReactHowler
          src={this.props.src}
          playing={this.state.isPlaying}
          onEnd={this._togglePlaying}
        />
        <button className={this.props.className} onTouchTap={this._togglePlaying}>
          {this.props.showIcon ?
            <i
              className={classnames("fa", {[`${this.props.playIcon}`]: !this.state.isPlaying, [`${this.props.pauseIcon}`]: this.state.isPlaying})}
              style={{marginRight: ".25em", marginLeft: ".25em"}}
            />
          : null}
          {this.props.showText ? !this.state.isPlaying ? this.props.playText : this.props.pauseText : null}
        </button>
      </span>
    );
  },

  _togglePlaying() {
    this.setState({isPlaying: !this.state.isPlaying});
  }

});

HowlerButton.propTypes = {
  /**
   * Audio file URL
   */
  src: React.PropTypes.string.isRequired,
  /**
   * Button class
   */
  className: React.PropTypes.string,
  /**
   * Show icon before text?
   */
  showIcon:  React.PropTypes.bool,
  /**
   * Icon shown when audio is not playing
   */
  playIcon: React.PropTypes.string,
  /**
   * Icon shown when audio is playing
   */
  pauseIcon: React.PropTypes.string,
  /**
   * Show text?
   */
  showText:  React.PropTypes.bool,
  /**
   * Text shown when audio is not playing
   */
  playText: React.PropTypes.string,
  /**
   * Text shown when audio is playing
   */
  pauseText: React.PropTypes.string
};

module.exports = HowlerButton;
```
