### ISSUE TITLE
props（ preload and playing） 

### ISSUE THREAD

**Issue by daiyang123456** [thangngoc89/react-howler#50]
react-howler is a React.js wrapper for howler.js (audio player)；

when both preload and playing are false，error will happen；

**Comment by Stenerson** [comment]
Hi @daiyang123456,
Can you provide more details? [One of the examples](https://github.com/thangngoc89/react-howler/blob/master/examples/react/src/players/NoPreload.js) has both preload and playing set to false on initial load and I'm not seeing any errors.

Live examples here: https://khoanguyen.me/react-howler/

**Comment by Stenerson** [comment]
@daiyang123456, I'm going to close this for now. If you have more details please reopen. Thanks!
