### ISSUE TITLE
Document `seek` prop and add to PropTypes

### ISSUE THREAD

**Issue by Stenerson** [thangngoc89/react-howler#59]
`props.seek` is not properly documented or included in the PropTypes.

Bonus: Add a seek example, possibly in the `FullControl` example.

**Comment by bundit** [comment]
I think the logic behind having seek as a prop is flawed. Just by passing the current seek position to the ReactHowler component creates circular logic. 

I.E. ReactHowler plays => changes seek => changes props => ReactHowler seeks => changes seek => changes props ... etc.

I tried modifying the FullControl example to be sure and it makes the audio stutter.

**Comment by Stenerson** [comment]
I think you're probably right @bundit. Do you have an alternative design suggestion?

**Comment by bundit** [comment]
I think it's fine exposing the seek method through the player ref as is, similar to other react media players (ex: [react-player](https://www.npmjs.com/package/react-player)) but the seek prop should probably just be removed. Then I could add seek control to the FullControl example.

**Comment by bundit** [comment]
What do you think @Stenerson?

**Comment by Stenerson** [comment]
Yeah, I think this makes sense @bundit. Removing the seek prop would be a breaking change of course, but I guess I'm not opposed to cutting a `5.0.0` for it. It's just a number, right? 😅 

Sounds like you're working on a PR 👍 I like it
