### ISSUE TITLE
Cannot read property 'playing' of undefined

### ISSUE THREAD

**Issue by jaredbuttars** [thangngoc89/react-howler#80]
I'm using react-howler in a typescript project. I get the error "EventName:TypeError: Cannot read property 'playing' of undefined" when the _handlePlay method is invoked.

@types/react-howler is installed for typings.

It looks like the `require('./howler')` in ReactHowler.js isn't loading correctly as `_howler4` and consequently `this.howler` are undefined throughout the ReactHowler.js script. 

Is this a bug or am I missing something? 

I setup the OnlyPlayPause example player as follows:

```
import * as React from 'react';
import ReactHowler from 'react-howler';

interface IPlayerState {
  playing: boolean;
}

export default class StationPlayer extends React.Component<{}, IPlayerState> {
  constructor(props:any) {
    super(props);

    this.state = {
      playing: false
    };
    
    this._handlePlay = this._handlePlay.bind(this);
    this._handlePause = this._handlePause.bind(this);
  }
  
  private _handlePlay():void {
    this.setState({
      playing: true
    });
  }

  private _handlePause():void {
    this.setState({
      playing: false
    });
  }

  public render(): React.ReactElement {
    return (
      <div>
        <ReactHowler src='https://15363.live.streamtheworld.com/KRSPFM_SC' playing={this.state.playing} />
        <button onClick={this._handlePlay}>Play</button>
        <button onClick={this._handlePause}>Pause</button>
      </div>
    );
  }
}
```

**Comment by Stenerson** [comment]
@jaredbuttars, I know it's been ages... (sorry!) were you able to resolve this? I'm scratching my head a bit wondering why you might be getting this error. 🤔
