### ISSUE TITLE
100% CPU in /react/src/players/FullControl.js

### ISSUE THREAD

**Issue by plog** [thangngoc89/react-howler#81]
Hi,

In [FullControl.js ](https://github.com/thangngoc89/react-howler/blob/master/examples/react/src/players/FullControl.js ) I noticed that the :
`handleOnPlay + renderSeekPos() + this.setState `
loop is consuming lots of CPU

setState() does cause the element to render

**Comment by Stenerson** [comment]
Closing this as I'm doing a little housekeeping. The FullControl player has some inefficiencies to be sure. If you want to update by moving `raf` into a subcomponent that only handles the seek position, I'd be happy to review and merge. For now I'm going to just leave is as an imperfect example of how the component might be used.
