### ISSUE TITLE
Is this compatible with hooks?

### ISSUE THREAD

**Issue by rchrdnsh** [thangngoc89/react-howler#82]
Hi,

Can this package be used with and/or is compatible with react hooks? Is there anything in the package that is dependent upon class based components?

thank you :-)

**Comment by Stenerson** [comment]
👋 @rchrdnsh to be honest I'm not sure but it seems like using class components is still supported when using hooks and there are no plans to not support this. Are you having a specific issue using this component with hooks in your project?
