### ISSUE TITLE
Audio doesn't work on iOS

### ISSUE THREAD

**Issue by alessandropisu** [thangngoc89/react-howler#86]
Hi everyone.
Chrome on iPhone doesn't start music automatically, i need to stop and start again. Is possible?

**Comment by webpty** [comment]
@alessandropisu, just as Safari did a while back, you now need user interaction on the page before playing sounds on Chrome. It's not actually an issue with react-howler.

---
#### Docs:
https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

---
#### My solution:
I've implemented a small welcome message with an "OK" button to force that initial interaction.
